# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Flowers"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# include timestamp in log format
logger_format: "%t [%P] %L @%D> %m in %f l. %l"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_flute"

engines:
  template_flute:
    filters:
      currency:
        options:
          int_curr_symbol: "EUR"
          p_cs_precedes: "0"
          mon_thousands_sep: "."
          mon_decimal_point: ","
          p_sep_by_space: "1"
      image:
        class: "Flowers::Filters::Image"

# session engine

session: "Storable"

# site locale

locale: sl_SI

# default payment method

payment_method:
  accountId: 99999
  trxuserId: 99998
  trxpassword: 0
  adminactionpassword: '5cfgRT34xsdedtFLdfHxj7tfwx24fe'
  app_security_key: 'testtest'
  wsdl_file: 'ipayment.wsdl'
  success_url: 'http://linuxia.de:3796/checkout-success'
  failure_url: 'http://linuxia.de:3796/checkout-payment'

# later we will add the hidden_trigger




# template: "template_toolkit"
# engines:
#   template_toolkit:
#     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

